{{ if .Values.terraform.enabled }}
apiVersion: terraformcontroller.cattle.io/v1
kind: Module
metadata:
  name: tf-module
  namespace: {{ .Release.Namespace }}
spec:
  git:
    url: {{ $.Values.terraform.module.url }}
    branch: {{ $.Values.terraform.module.branch }}
{{ end }}