admin:
  image: hobbyfarm/admin-ui:0.0.13
ui:
  image: hobbyfarm/ui:0.3.1
  # configMapName: ui-config
gargantua:
  image: hobbyfarm/gargantua:v0.0.3

ingress:
  enabled: false
  annotations: {}
  hostnames:
    # ui: example.com
    # admin: admin.example.com
    # backend: hf.example.com
    # shell: shell.example.com
    ranchervm: {}
      # frontend: vm.example.com
      # backend: vmapi.example.com
  tls:
    enabled: true
    # defaults to ingress.hostnames if empty
    hosts: []
    secretName: hobbyfarm-cert

# seed with some example data
seed:
  enabled: false

# https://github.com/rancher/terraform-controller
terraform:
  enabled: true
  executor:
    image: oats87/terraform-controller-executor
    tag: "hfv1"
  controller:
    image: hobbyfarm/terraform-controller
    tag: "12032019"

  # one of: ranchervm (broken), google, aws, vsphere (untested), do (untested)
  provider: aws

  ranchervm:
    module: https://github.com/hobbyfarm/tf-module-rvm
    image: rancher/vm-ubuntu:16.04.5-server-amd64
    endpoint: "http://backend.ranchervm-system:9500"
    access_key: ''
    secret_key: ''

  google:
    module: https://github.com/boxboat/tf-module-google
    # credentials: |

  aws:
    module: https://github.com/hobbyfarm/tf-module-aws
    image: ami-04763b3055de4860b
    region: us-east-1
    # access_key:
    # secret_key:
    # subnet:
    # vpc_security_group_id:

  vsphere:
    module: https://github.com/hobbyfarm/tf-module-vsphere

  do:
    module: https://github.com/dramich/domodule

# https://github.com/hobbyfarm/vm
ranchervm:
  enabled: false
  nic: "eth0"
  bridge: "en0"
  # bridge: "docker0"
  image:
    vm: rancher/vm:v0.2.0
    frontend: rancher/vm-frontend:v0.2.0
    novnc: rancher/vm-novnc:v0.2.0
    tools: rancher/vm-tools:v0.2.0
