apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: admin-ui
  template:
    metadata:
      labels:
        component: admin-ui
    spec:
      containers:
        - name: admin-ui
          image: {{ $.Values.admin.image }}
          {{ if $.Values.insecure }}
          args:
            - --insecure
          {{ end -}}
          env:
            - name: HF_SERVER
              {{ if $.Values.ingress.enabled }}
              value: {{ $.Values.ingress.hostnames.backend | quote }}
              {{ else }}
              value: gargantua
              {{ end }}
