apiVersion: hobbyfarm.io/v1
kind: User
metadata:
  name: admin
spec:
  id: admin
  email: admin
  password: $2a$10$33fQs0G.lHQdDAsdoECgA.8iYvNtyJ2XC2AmvR5x6ZkzxSuKXyfFm
  admin: true
  access_codes:
  - training