{{ if $.Values.syncer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncer
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: syncer
  template:
    metadata:
      labels:
        component: syncer
    spec:
      containers:
        - name: syncer
          image: {{ $.Values.syncer.image }}
          args:
            {{- if $.Values.syncer.replace }}
            - --replace
            {{- end }}
            {{- if $.Values.syncer.webhook.enabled }}
            - --webhook
            {{- if $.Values.syncer.webhook.secret }}
            - {{ $.Values.syncer.webhook.secret }}
            {{- end }}
            - --service
            - {{ $.Values.syncer.webhook.service }}
            {{- end }}
          env:
            {{- range $key,$value := $.Values.syncer.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          {{- if $.Values.syncer.secret }}
          envFrom:
            - secretRef:
                name: {{ $.Values.syncer.secret }}
          {{- end }}
{{- end }}