{{ if $.Values.syncer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncer
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: syncer
  template:
    metadata:
      labels:
        component: syncer
    spec:
      containers:
        - name: syncer
          image: {{ $.Values.syncer.image }}
          args:
            {{- if $.Values.syncer.replace }}
            - --replace
            {{- end }}
          volumeMounts:
            - name: repo
              mountPath: /repo
        - name: git-sync
          image: {{ $.Values.syncer.gitSync.image }}
          imagePullPolicy: Always
          volumeMounts:
            - name: repo
              mountPath: /tmp/git
          env:
            {{- range $key,$value := $.Values.syncer.gitSync.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          {{- if $.Values.syncer.gitSync.secret }}
          envFrom:
            - secretRef:
                name: {{ $.Values.syncer.gitSync.secret }}
          {{- end }}
      volumes:
        - name: repo
          emptyDir: {}
{{- end }}