{{- if $.Values.syncer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: syncer
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: syncer
  ports:
    - name: http
      port: 80
{{- end }}