apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sshd
  name: sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
        version: v0.0.1
    spec:
      containers:
      - image: hobbyfarm/local-sshd:latest
        imagePullPolicy: Never
        name: sshd
