apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tf-git
  name: tf-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-git
  template:
    metadata:
      labels:
        app: tf-git
        version: v0.0.1
    spec:
      containers:
      - image: hobbyfarm/local-tf-git:latest
        imagePullPolicy: Never
        name: tf-git
