apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: environments.hobbyfarm.io
spec:
  group: hobbyfarm.io
  version: v1
  names:
    kind: Environment
    plural: environments
    singular: environment
    shortNames:
    - e
  scope: Cluster