apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scheduledevents.hobbyfarm.io
spec:
  group: hobbyfarm.io
  version: v1
  names:
    kind: ScheduledEvent
    plural: scheduledevents
    singular: scheduledevent
    shortNames:
    - se
  scope: Cluster