apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualmachinetemplates.hobbyfarm.io
spec:
  group: hobbyfarm.io
  version: v1
  names:
    kind: VirtualMachineTemplate
    plural: virtualmachinetemplates
    singular: virtualmachinetemplate
    shortNames:
    - vmt
    - vmtemplate
    - vmtemplates
  scope: Cluster